/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { Carousel } from "./index"

// @ts-ignore
export function indexTemplateHtml(this: Carousel<any>) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"carousel",style:(_vm.containerStyle)},[_c('div',{staticClass:"main",style:(_vm.mainStyle),on:{"touchstart":function($event){_vm.touchstart($event)},"touchmove":function($event){_vm.touchmove($event)},"touchend":function($event){_vm.touchend($event)}}},[_c('ul',{ref:"ul",style:(_vm.ulStyle),on:{"mouseenter":function($event){_vm.pause()},"mouseleave":function($event){_vm.start()}}},_vm._l((_vm.data),function(item,i){return (i >= _vm.currentIndex - _vm.actualCount && i < _vm.currentIndex + _vm.actualCount * 2)?_c('li',{key:i,style:(_vm.liStyle)},[_c(item.component,{tag:"component",attrs:{"data":item.data}})],1):_vm._e()}),0)]),_vm._v(" "),_c('div',{staticClass:"left",style:(_vm.leftStyle),on:{"click":function($event){_vm.moveLeft(_vm.actualCount)},"mouseenter":function($event){_vm.mouseenterLeft()},"mouseleave":function($event){_vm.mouseleaveLeft()}}}),_vm._v(" "),_c('div',{staticClass:"right",style:(_vm.rightStyle),on:{"click":function($event){_vm.moveRight(_vm.actualCount)},"mouseenter":function($event){_vm.mouseenterRight()},"mouseleave":function($event){_vm.mouseleaveRight()}}})])}
// @ts-ignore
export var indexTemplateHtmlStatic = [  ]
// tslint:enable
